Traceback (most recent call last):
  File "logistic_reg.py", line 72, in <module>
    le = le.fit(types)
  File "/usr/lib64/python3.4/site-packages/sklearn/preprocessing/label.py", line 112, in fit
    y = column_or_1d(y, warn=True)
  File "/usr/lib64/python3.4/site-packages/sklearn/utils/validation.py", line 562, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()
